### ISSUE TITLE
Cannot import anything

### ISSUE THREAD

**Issue by UberGrainy** [TheCrazyT/BlenderMhwModelImporter#8]
Traceback (most recent call last):
  File "Blender Foundation\Blender\2.79\scripts\addons\BlenderMhwModelImporter\operators\mhw_model.py", line 1388, in execute
    bpy.ops.object.mode_set(mode='OBJECT')
  File "Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1

Edit: It works if I delete that line at 1388.

**Comment by TheCrazyT** [comment]
Was your scene empty?

Because i added this line to avoid exactly the same error when importing in pose mode.(thats why i set it to object mode that does not cause trouble)
So my guess is that this error can happen if no object exist or no object is active/selected.(still a bug, but need to know if this is the problem)
